apiVersion: v1
data:
    tele_token: ENC[AES256_GCM,data:yBgxFlQ4cLSZ6+d+s+VUzFgYMRS1jNPLJf5BXu7h9kyb9IVmuK8XvXo9GdwYjI3MEzw8oXyVFLQoACpewHpbSw==,iv:IyjUzLwYxdQ3Y3KfrU3xMmSvHx3nP3QXhR0kGX54yV8=,tag:KsDTXcONt68uMKWWHUtpRw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tbot
    namespace: demo
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/booming-crowbar-407418/locations/global/keyRings/sops-flux2/cryptoKeys/sops-key-flux
          created_at: "2024-01-23T10:10:35Z"
          enc: CiQASmYm0yKPBkxHRDaAzWMKcjElFBkkswtLdHLe/2VhQSaDwPQSSQCEftTmiepH8z/BAiaQPokXE3myrLzl9P81hCoXb5Tq6e4nD/TJQ1bNauPrXKAzbMFWKbO7l2xPjP7DAI8Han6y1oyXkOfmk4o=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-23T10:10:36Z"
    mac: ENC[AES256_GCM,data:s2p08QJZHp9VTNth7Fsx1NMeOZp4UIop1zSUFblwHBCyCMyvFc1eVgFFwB4gtNlQj7n2GWgd0iLyIlgm8IXeQtSQSpsmmm+UGlolSJxgMPT1Oh8oQojfI/lw31w9/+ciFDFPkreMr7DeLMZfWjoTcrZPu89FVX98M2q+8Fsed1o=,iv:87PWyptt4u2stadNsv+h7q0Q+1ApWDnEagyY84k8+Aw=,tag:imvWPY6Iy9cu2pwWwt4WMg==,type:str]
    pgp: []
    encrypted_regex: ^(tele_token)$
    version: 3.8.1
