apiVersion: v1
data:
    tele_token: ENC[AES256_GCM,data:LzjfEzkA0ge92idqLZ0URrBI48WNXPA+ZLZmaQuc6X50Ve/wfQE4+SeeFpQipxbGjPhbb8zwfLX7u2SaW9eqFw==,iv:Gj7ADN+lbMiJVRBgTDTUSaquJajJ+m4/IdyDtqEDK00=,tag:H3QwfyyOzOR3Bk1F+RhXbQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tbot
    namespace: demo
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/booming-crowbar-407418/locations/global/keyRings/sops-flux2/cryptoKeys/sops-key-flux
          created_at: "2024-01-23T10:21:39Z"
          enc: CiQASmYm0wxdqJNQ8oCwC1rc1oHp0GqIYA9Z5R/dnr1ktQ9PM6wSSQCEftTm2usfblPUQ0mJHUTVnKYQQTMxvtzsO0J8N+Je3zqRqUkGxF4R8Eu7exZqeHwYrd/12EDyz5KlCKDDb2SbdH3csNUcsb0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-23T10:21:39Z"
    mac: ENC[AES256_GCM,data:16MwF/pv6C8wLbUH5IO7kKZaG5UA/AV9OlSeW6dpSOBph0km8oZYZylgCLzFLzRNe1B8xhaCFAg51aXp0EyuiK64mpLBXyNDWwwzKYbBI1F+Ns696fOfAjbTof3Q2PnyNC7HSsl8OekM+JZVZTMcmgafmSFqf0dOZ7YFuiTBu9Y=,iv:QEIIX+UgoF41/cw+1bZwkqSR8AYGsk5eSPqtcdFjwbM=,tag:xEkNtfCV/eEMfUVHkPPdXQ==,type:str]
    pgp: []
    encrypted_regex: ^(tele_token)$
    version: 3.8.1
