apiVersion: v1
data:
    tele_token: ENC[AES256_GCM,data:RVpQaQUry6Quq5TyeY30CcovGHD/a/rSfskT9RZ4KM4qL9tLXs1g1vi6IoX8zs1Z39gND8DVLsY345t/DJH6Qw==,iv:+cY0UlcJWuJLlvB1zsJQLlGQ8MzAYsVy8PqYbucjpf8=,tag:XniWjxj8OIm//4J1aEPXCA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tbot
    namespace: demo
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/booming-crowbar-407418/locations/global/keyRings/sops-flux2/cryptoKeys/sops-key-flux
          created_at: "2024-01-23T10:23:11Z"
          enc: CiQASmYm0+iZklVfR+0LK2FCXh9eo3lYm4l84J/xyAUDNNFqeCMSSQCEftTmr03Za5q5JgpQ3dvaw5OH8md79MFe5gfnNxDoocfQ5KoDfZhHLXahLdO56/8itcbMm1U7m/4GZghlOrdUFr5Ae72qZhI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-23T10:23:12Z"
    mac: ENC[AES256_GCM,data:xk5ih1lLWLGo89B/gQaz9S8S5FmB/RGrAa00K++NuL7lX0V4dqF0z5VLnvnBnssDVFl7Dtl9M/ZsEiyJU7C0XFRiwo6DDVj5e1Dza7F61QOfM/u1xn7maSsTRB66Ntw6OpKxulcHqB5V2F5V6adOY4DnVBiSCViSr4PD4OLs2AI=,iv:HyzB2EOo6OmLdOuHuIETiFkmMDFoDBL5mU5mKMcAwNE=,tag:bUgKlHltxNzXZRwTzPzIvw==,type:str]
    pgp: []
    encrypted_regex: ^(tele_token)$
    version: 3.8.1
