name: List services in GCP
on: [push]

permissions:
  id-token: write
  contents: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'repo'
      name: 'Checkout repository'
      uses: actions/checkout@v3
      
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v2'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/448492338462/locations/global/workloadIdentityPools/workload-example/providers/github'
          service_account: 'github@booming-crowbar-407418.iam.gserviceaccount.com'
             
    - id: 'secrets'
      name: 'Get Secret'
      uses: 'google-github-actions/get-secretmanager-secrets@v2'
      with:
        secrets: |-
          token:booming-crowbar-407418/teletoken
      
    - id: 'token'
      name: 'Echo Token'
      env:
        TOKEN: '${{ steps.secrets.outputs.token }}'
      run: |-
        kubectl create secret generic tbot --from-literal=tele_token=$TOKEN -n demo --dry-run=client -o yaml > tbot-secret.yaml
        kubectl create secret docker-registry ghcr-secret -n demo --docker-server=ghcr.io --docker-username=lyalyukev --docker-password=$secrets.GITHUB_TOKEN --dry-run=client -o yaml > ghcr-secret.yaml

    - id: 'download_sops'
      name: 'Download SOPS'
      run: |-
        if [ ! -f "sops" ]; then
          curl -LO https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
          mv sops-v3.8.1.linux.amd64 sops
          chmod +x sops
        fi
        
    - id: 'encrypt_secrets'
      name: 'Encrypt Secrets'
      run: |-
        ./sops -e -gcp-kms projects/booming-crowbar-407418/locations/global/keyRings/sops-flux2/cryptoKeys/sops-key-flux --encrypted-regex='^(tele_token)$' tbot-secret.yaml > ./clusters/demo/tbot-secret.yaml
        ./sops -e -gcp-kms projects/booming-crowbar-407418/locations/global/keyRings/sops-flux2/cryptoKeys/sops-key-flux --encrypted-regex='^(data|.dockerconfigjson)$' ghcr-secret.yaml > ./clusters/demo/ghcr-secret.yaml
   
    - id: 'add_files_to_repo'
      name: 'Add files to repo'
      run: |-
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add tbot-secret-en.yaml ghcr-secret-en.yaml
        git commit -am "Add files secrets"
        git push

        
        
